#!/bin/bash

# Lets Encrypt
if [ -z "$EMAIL" ] || [ -z "$DOMAIN" ]; then
 echo "You need the \$EMAIL and the \$DOMAIN Variables"
else
 certbot certonly --webroot -w /var/www/html -d $DOMAIN --email $EMAIL --agree-tos --quiet
 ln -s /etc/nginx/sites-available/default-ssl.conf /etc/nginx/sites-enabled/

 # change nginx for webroot and domain name
 sed -i "s/##DOMAIN##/${DOMAIN}/g" /etc/nginx/sites-enabled/default-ssl.conf
 sed -i "s#root /var/www/html;#root ${WEBROOT};#g" /etc/nginx/sites-available/default-ssl.conf

if [[ "$HTTPS_REDIRECTION" == "1" ]]; then
 echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
    }";
fi

 nginx -s reload
fi
