#!/bin/bash

if [ -z "$EMAIL" ] || [ -z "$DOMAIN" ]; then
 echo "You need the \$EMAIL and the \$DOMAIN Variables"
else
 certbot certonly --webroot -w /var/www/html -d $DOMAIN --email $EMAIL --agree-tos --quiet
 ln -s /etc/letsencrypt/live/$DOMAIN/privkey.pem /etc/letsencrypt/live/
 ln -s /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/
 ln -s /etc/nginx/sites-available/default-ssl.conf /etc/nginx/sites-enabled/

 nginx -s reload
fi
